### PR TITLE
Update Bitcrush

### PR DESCRIPTION
**Pull request by HON95**
Tested and working.

## Changes
- Use valid signal.
- Tune rate reduction wrt. control input.

### CODE REVIEW

**Comment by kalkins** [comment]
I testes ut, but I couldn't get it to work with RegInit. I tried using the reset switch.

--
 Sindre Stephansen
 sindre@sindrestephansen.com

**Comment by HON95** [comment]
> I testes ut, but I couldn't get it to work with RegInit. I tried using the reset switch.

How exactly did it not work? Was the "reset jumper" connected? Even if the counter register starts at a random value, it should reset itself to a valid value rather quickly.

**Comment by kalkins** [comment]
By failed I mean that it didn't play any sound at all, unless I changed it to RegNext.

Do you mean the reset jumper from pinout 15? I thought the MCU handled resets now, and assumed it reset the FPGA too when the button was pressed. RegInit it kind of weird, at least when reset isn't done properly, as it won't overwrite the register with a new value. That's the reason we've used RegInit up til now, as it doesn't care about reset.

--
 Sindre Stephansen
 sindre@sindrestephansen.com

**Comment by kalkins** [comment]
Ok, I merged in master, and it seems to work perfectly now without the reset jumper

**Pull request merged**
